/*
Navicat MySQL Data Transfer

Source Server         : 127.0.0.1
Source Server Version : 50718
Source Host           : localhost:3306
Source Database       : littledot_web

Target Server Type    : MYSQL
Target Server Version : 50718
File Encoding         : 65001

Date: 2021-12-01 01:17:55
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `products`
-- ----------------------------
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) DEFAULT NULL,
  `contents` text,
  `type` tinyint(3) unsigned DEFAULT NULL,
  `types` tinyint(3) unsigned DEFAULT NULL,
  `description` varchar(128) DEFAULT NULL,
  `price` decimal(10,0) unsigned zerofill DEFAULT NULL,
  `ttm` date DEFAULT NULL,
  `position` tinyint(3) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of products
-- ----------------------------
INSERT INTO `products` VALUES ('1', 'MK2', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nLittle Dot MK II uses the 6J1 pentode as the pre-amp tubes, and the double diode triode 6n6. This combination forms a SEPP (Single-Ended Push Pull) OTL Class-A amplifier. The SEPP circuit design greatly increases sound quality, dynamic range, output impedance, and lower distortion over the Little Dot II.\r\n\r\nThe Little Dot MK II now also provides gain control of 3, 5, and 10 via internal DIP switches for fine-tuning so you can maximize synergy with almost any headphone you have, whether it be 32 ohms or 600! Not only it works great as a headphone amplifier, it also works as a pre-amplifier, and the user can link it to your power amplifier to tune your current system. The double anodic aluminum oxidation provides chassis quality touch and smooth surface.\r\n\r\nThe Little Dot MK II also gives user to enjoy tube-rolling, you can stick with the original 6JI, or you could swap with WE403A/B, GE5654, M8100, CV4010, EF95, and etc. At its factory jumper setting, and with jumper pins shorted, EF92, CV131, and all equivalents and drop-in replacements!\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n1. <A HREF=\"https://www.head-fi.org/showcase/little-dot-mk-ii.12097/\" target=\"_blank\">Review of Little Dot MKII: Little Dot MK II Review @ Head-Fi </A>\r\n2. <A HREF=\"https://www.youtube.com/watch?v=65y_2yc_vZs&t=7s/\" target=\"_blank\">Cheap Tubes for BIGGER Soundstage? Little Dot MK II Review! @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input: Gold-Plated Unbalanced Phono (RCA) Jacks\r\n• Output: 1/4″ Gold-Plated Stereo Headphone out, RCA Jacks (for pre-amp use)\r\n• Pre-Amplifier Gain: 3-10x (also controlled via gain switches)\r\n• Frequency Response: 300 ohm (-1dB)\r\n• THD+N: 0.1% (50mW into 300 ohms)\r\n• Output Power:\r\n	a) 300 mW   (600/300 Ω)\r\n	b) 200 mW   (120 Ω)\r\n	c) 100 mW   (32  Ω)</div>\r\n• Output Impedance:\r\n• Suitable Headphone Impedance: 32Ω – 600Ω\r\n• Pre-amp impedance: 10 K ohm\r\n• Fuse: 1A (within the power plug slot)\r\n', '1', '1', '•OTL Class-A <BR>\r\n•Use as pre-amp', '0000000080', '2008-08-08', '1');
INSERT INTO `products` VALUES ('2', 'LD1+', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe Little Dot I+ is a hybrid transistor-vacuum tube headphone amplifier, which combines the smooth, musical sound of tubes with the high output current of transistors. The vacuum tube stage is run in Class-A, the MC33078 operational amplifier (socketed) provides voltage amplification, and BD139/BD140 transistors serve as output buffers.\r\n\r\nThe Little Dot I+ is specifically designed and optimized for driving low impedance headphones that require high current to perform to their full potential. Depending on how the switches are configured, three different families of vacuum tubes can be used (EF95, EF92, and 408A). With two gain settings and DIP switches for vacuum tube rolling, the Little Dot I+ offers versatility and incredible sound quality in a tiny footprint!\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<A HREF=\"https://www.youtube.com/watch?v=DDSPXOyyUt4&t=96s\" target=\"_blank\">LittleDot 1+ Review: Best Tube Amp under $170?  @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input: Gold-Plated Unbalanced Phono (RCA) Jacks\r\n• Output: 1/4\" Gold-Plated Stereo Headphone out\r\n• Vacuum  Tubes: 6JI (default) EF92 or WE408 as upgrades\r\n• Frequency Response: 10HZ - 50KHz (-3 dB)\r\n• THD+N: \r\n	0.2%: 1     Vrms @ 1000Hz\r\n	0.6%: 3     Vrms @ 1000Hz\r\n	1.0%: 5     Vrms @ 1000Hz\r\n• Gain: 3.5x, 7x\r\n• Power Output: \r\n	800mW @ 32Ω\r\n	300mW @ 120Ω\r\n	150mW @ 300Ω\r\n• Recommended Headphone Impedance: 8 – 600Ω\r\n• Power Consumption: 15VA\r\n• Size: 180x97x10(h) mm\r\n• Weight: 1.5 kg', '2', '2', 'Hybrid tube headphone amp', '0000000080', '2008-08-08', '2');
INSERT INTO `products` VALUES ('3', 'MK3', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nMK3 is an “all vacuum tube” amplifier. \"ALL\" means that its pre and post stage are tube amplification. The MK3 can both work as headphone amplifier and vacuum tube pre-amplifier. It\'s design with SEEP circuit frame. Input stage used GE5654 form GE™, and final output stage is 6H6π. This framework guaranteed both high-current to drive low resistance headphones and high voltage swing for high resistance headphones.\r\n\r\nMK3 is a long-life product in our product line, it is a classic design of SEEP circuit frame, and all the components in this circuit are famous and reliable. The volume control potentiometer from ALPS™,Japan. E-Cap as filter capacitors from RUBYCON™,Japan. Coupling capacitance from ERO™, Germany. Final stage output capacitors form CHIEMI-COM™,Germany and calibrating capacitors form WIMA™,Germany.\r\n\r\nIt has been once praised as “Lucky Product” by Stereophile magazine.\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n1. <A HREF=\"https://www.youtube.com/watch?v=7MeH9C4_Zi0\" target=\"_blank\">Little Dot MK 3 Tube Amplifier Review and Tube Rolling @ Youtube</A>\r\n2. <A HREF=\"https://www.youtube.com/watch?v=wO2il7SRzn4\" target=\"_blank\">Little Dot MK III Headphone Tube Amplifier Review @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input ports: RCA*2\r\n• Output ports: \r\n	6.35mm(1/4inch)x1\r\n	Pre-Amplifier) RCA x2 \r\n• Magnification: 3x~10x\r\n• Frequency Response: 12Hz --- 100KHz (300odm -1dB)\r\n• THD: 0.15%  (300odm 80mW)\r\n• SNR: 96dB\r\n• Output Power: \r\n	100mW@32Ω\r\n	300mW@120Ω\r\n	350mW@300/600Ω\r\n• Output resistance: 10KΩ for pre-amplifier, 32Ω~600Ω for headphones\r\n• Fuse: 1A (inside power supply socket)\r\n• Size: 270(L)x175(W)x123(H)mm\r\n• Weight: 3Kg\r\n', '1', '1', '•OTL Class-A <BR>\r\n•Use as pre-amp', '0000000090', '2008-08-08', '2');
INSERT INTO `products` VALUES ('4', 'LD-H1', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nLD-H1 is a tube-transistor combined fully balanced headphone amplifier. The front stage tube part is the famous NOS tube 6SN7 from SYLNAVIA™,USA. Back stage part is designed with entire discrete symmetrical Class-A circuit without any molectron. This circuit has better Instantaneous response speed and lower crossover distortion. LD-H1 has a compatible framework for both balanced and non-balanced system. The machine contained XLR balanced input/output ports and non-balanced RCA input and 6.35mm output.\r\n\r\nThe design scheme LD-H1 is “double single channel”. From power supply to amplifier, every circuit unit is exactly independent to avoid crosstalk. Combined framework keeps advantages form both tube and transistor. Especially it performs excellently when driving low resistance headphones. \r\n\r\nAs a balanced amplifier, LD-H1 contained 4 independent amplification units with own transformer supply. The current direction through each amplification unit is opposite. This scheme offsets the fluctuation of voltage, makes power supply more stable and reduces power supply internal resistance intermodulation. It affects the sound performance more clear and roomy. \r\n\r\nThe components of this amp are also very well chosen. Classic style appearance with textured wooden cover. Famous BC E-Cap as filter capacitors from Philips™. M-cap EVO audio special-purpose coupling capacitance from Mundorf™, Germany.\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<A HREF=\"https://headfonics.com/little-dot-ld-h1-review/\" target=\"_blank\">Little Dot LD H1 Review @ Headfonics</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input Ports: RCA x2\r\n• Balance: XLR 3p x2\r\n• Unbalanced: RCAx2\r\n• Output Terminal:\r\n	Balance: XLR 4p x1\r\n	Unbalanced: 6.35mm x1\r\n	Pre-output: Balance: XLR 3p x2\r\n	Input impedance: 10 K ohm\r\n• Distortion: 0.001% (output: 2V rms 1000Hz)\r\n• Signal to noise ratio: 108dB\r\n• Frequency response: 10Hz – 50KHz (-0.1dB)\r\n• Output Power:\r\n	5W (32 Ω)\r\n	1.8W (120 Ω)\r\n	0.8W (300 Ω)\r\n	0.4W (600 Ω)\r\n• Adapted headphone impedance: 16 ohm ~ 600 ohms\r\n• Gain:\r\n	Gain = HIGH: 9\r\n	Gain = LOW: 4.5\r\n• Power consumption: 25 VA\r\n• Size: 300x210x140(H)mm\r\n• Weight: 4.5Kg', '2', '2', 'The flagship hybrid tube amp', '0000000150', '2017-08-08', '5');
INSERT INTO `products` VALUES ('5', 'LD-Y2', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe LittleDot LD-Y2 is a headphone and loud speaker dual-use amplifier with 300B tubes. In order to achieve the best performance, its power unit and amplification unit are independent. The power supply of LD-Y2  uses the tube rectification. It\'s come from Soviet Union, 5U4G. \r\n\r\nAs we all know, 300B is a very good power tube for the amplifier. As the core of  LD-Y2, we chooses JJ300B, which is the industry-leading, from Czech. In the selection of the preamp tube, according to the original recommendation of 300B usage, we choose RCA 6SH7 as the preamp tube for it.\r\n\r\nThe other parts of LD -2 are also very elaborate, including:\r\n  1. Swiss Lundal™ input transformer\r\n  2. Mundorf™  oil immersed capacitor\r\n  3. Kiwame™ resistors\r\n  4. Germany WBT™ silver solder\r\n  5. Japan Furutech™ AC Socks\r\n  6. DACT™ Audio Attenuators\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<div style = \"background: #efefed;\">	\"The LD Y2 focuses on curing the low-frequency problem for all kinds of hard to driver headphones. The medium and high frequency details are excellent, the medium frequency density is moderate, and the “tube smell” is  obvious. It can be said that it brought quite a surprise, especially the  Beyerdynamic T1 and HiFi-Man HE1000, which are the best performance I\'ve ever heard.\" </div> ---- from **af2000** @ erji.net\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input terminals.\r\n• XLR balanced input x2\r\n• RCA unbalanced input x2 \r\n• Headphone output terminals.\r\n	XLR (4 cores) x1 (balanced headphone output)\r\n	6.35 (3 core) x1 (unbalanced headphone output)\r\n• The speaker output terminals: a total of four left and right channels\r\n• Distortion: 0.1% (1000Hz) \r\n• Signal-to-noise ratio: 98dB\r\n• Frequency response:\r\n	20Hz - 20KHz (-0.2dB)\r\n	10Hz - 50KHz (-2dB) \r\n• Output power:\r\n	10W (8 Ω) 	\r\n	6W (120 Ω)\r\n	3W (300 Ω)\r\n• Amplification:\r\n	GAIN=HIGH: 7\r\n• GAIN=LOW: 4\r\n• Power consumption: 150 VA\r\n• Size: 350x210x220(h)mm (This is the size of one unit, the amp + power supply total of two units)\r\n• Weight: 23 Kg (including the amp + power supply, together with the total weight of packaging and accessories)', '4', '1', '300B headphone & speaker amplifier', '0000000199', '2017-08-08', '2');
INSERT INTO `products` VALUES ('6', 'DAC-7', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nDue to LittleDot Audio years of analog audio design experience, our DAC products also have a unique feature that we call it \"analog taste\".\r\n\r\nThe flagship ES9038PRO SABRE DAC sets a new benchmark for audio excellence with the industry’s highest dynamic range (DNR), in a 32-bit, 8-channel DAC. These parameters make the ES9038PRO excellent in terms of resolution performance. With our experience in analog circuits, the DAC7 strikes a good balance between high detailing and natural musicality.\r\n\r\n<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/DAC-7/6.jpg\" style=\"max-width:100%\">\r\n</div>\r\n\r\n', '5', '1', 'Flagship ESS9038PRO DAC', '0000000192', '2018-08-08', '1');
INSERT INTO `products` VALUES ('7', 'LDP-1000', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThis is the HiFi top purifying power supply, it convert the AC power to DC power, through the MCU composite waveform convert to the stable AC power at 50 or 60Hz.\r\n\r\nThis is our third generation of power regenerator, and we’ve adopted SCALE™ IGBT method from Power Intergration. The LDP-1000 has the following functions, automatic recovery after over-current protection, which gives the regenerator more reliable than that of the previous generation products.\r\n\r\nIt has the function of automatically stable the frequency and voltage, active energy compensation, over-current protection, automatic recovery. With this method, we can avoid the disadvantages of dynamic compression, supply our equipment with clean power and the background will be pitch black.\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Output Power: 1000VA\r\n• Power Supply Distortion: <= 1%\r\n• Power Supply Stability: 2%\r\n• Power Factor: 0.95\r\n• Maximum Efficiency: 95%\r\n• Voltage Tolerance Boundary: 185 – 255 V\r\n	From no-load to 100% full load, the instantaneous output voltage fluctuations < 6%, recovery cycle less than 2 sine wave cycle.\r\n• Output voltage: 110V or 220V\r\n• Output frequency: 50Hz or 60Hz\r\n• Output Sockets: 8 US sockets\r\n	Protection function: It has conventional protection functions such as overheating, overload, short circuit, over-voltage, under-voltage, etc.\r\n	Note: Due to the weight of the power regenerator, it is very difficult for us to lower the price of this wonderful unit. However, if you’re not in a rush, ocean freight will be able to save you a lot of money. The downside of that is that we will not be able to provide you any tracking number, and it could take up to 40 days for your product to arrive. Please contact us if you’d wish to proceed with ocean freight, thank you!\r\n', '6', '1', 'Purification and regeneration power supply', null, '2018-08-08', '1');
INSERT INTO `products` VALUES ('8', 'CDP-2', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe Littledot CDP-2 is a CD turntable with a Philips DAISY GF-8 CD core. With low distortion, high resolution features, delicate and sweet sound quality, as a compact CD turntable, it also has outputs like BNC/RCA/fiber interface. There is also an aluminum alloy remote control.\r\n\r\nPhilips DAISy GyFalcon 8, a high end module dedicated to CD applications. It has been meticulously tested to reach an excellent playability and reliability.  A DSA high level interface is available for this module. \r\nGF-8 Key features: \r\n	• Extra slim loader\r\n	• Excellent reliability\r\n	• Low mechanical noise\r\n	• DSA Interface (High Level protocol)\r\n	• Extremely good playability and disc acceptance\r\n	• Compatibility with protected discs\r\n	• I2S and SPDIF signals available\r\n	• Fast average access time\r\n	• MP3 DISC playback\r\n	• Excellent ratio quality/price\r\n	• RoHS compliant\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• S/PDIF output terminals.\r\n• BNC output socket\r\n• RCA output socket\r\n• Optical output socket\r\n• Coaxial output impedance:  BNC/RCA: 75Ω\r\n• S/PDIF output level:  BNC/RCA : > 500 mV (rms)\r\n• Output sampling frequency:  44.1 KHz\r\n• Power Consumption:\r\n	Working: 10 VA\r\n	Standby: 3 VA\r\n• Fuse: 1A (built-in in the power socket)\r\n• Size: 275X217X61(H) mm\r\n• Net weight: 2 .1Kg  \r\n• Gross weight: 2.9 Kg', '7', '1', 'Philips Daisy GF8 Module', '0000000011', '2010-08-08', '1');
INSERT INTO `products` VALUES ('9', 'CU-RAD', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/CU-RAD/page1.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page2.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page3.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page4.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page5.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page6.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page7.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page8.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page9.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page10.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page11.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page12.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page13.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page14.jpg\" style=\"max-width:100%\">\r\n</div>\r\n', '8', '1', 'Multiayer Nanomaterial IEM', '0000000012', '2020-01-01', '2');
INSERT INTO `products` VALUES ('10', 'LD-ZERO', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/LD-ZERO/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page6.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page7.jpg\" style=\"max-width:100%\">\r\n</div>', '2', '1', 'All In One headphone amp with DAC & Bluetooth', '0000000111', '2021-11-11', '1');
INSERT INTO `products` VALUES ('11', 'MK3-SE', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/MK3-SE/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page6.jpg\" style=\"max-width:100%\">\r\n</div>\r\n\r\n', '2', '1', 'Full balanced hybrid tube amp', '0000000123', '2008-08-08', '4');
INSERT INTO `products` VALUES ('12', 'LD3-SE', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe Little Dot LD III SE uses the NOS Telefunken EL152 antique tubes as power output tubes; for pre-amplification, it uses the Western Electric WE408A . These tubes are now legendary “artifact”, and we only have 150 sets of new NOS inventory, so the machine is a true “limited edition.”\r\n\r\nThe machine uses a specially designed Z11 core output transformer, coupling capacitor uses Mundorf silver oil capacitors, and resistors are Kiwame for AUDIO-specific resistors. Teflon silver wire is used within the machine, and the German silver solder. Headphone output section, using our developed “intelligent recognition impedance” proprietary technology that can automatically detect impedance headphones, and switch to the appropriate interface.\r\n\r\nTelefunken EL152 output power (larger than the famous 300B); sound excellent, with so much musical detail. Such tubes are antique collection!\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<A HREF=\"https://www.youtube.com/watch?v=ZbZs2BoX39k\" target=\"_blank\">These are Limited Version for a Reason ! Little Dot LD3SE tube integrated amplifier review by Jay\'s iyagi @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input terminals:\r\n	RCA x2\r\n• Output terminal :\r\n	1,6.35 x1 (headphone output)\r\n	2, RCA x2 (Pre Out)\r\n• Distortion: 0.1% (1000Hz)\r\n• Signal to Noise Ratio: 96dB\r\n• Frequency response:\r\n	1,20Hz – 20KHz (-1dB)\r\n	2,20Hz – 40KHz (-2dB)\r\n• Output power:\r\n	Maximum output power: 10W + 10W\r\n• Rated output power:\r\n	10W (8 Ω)\r\n	6W (32 Ω)\r\n	2W (300 Ω)\r\n• Magnification:\r\n	GAIN = HIGH: 10\r\n	GAIN = LOW: 5\r\n• Power consumption: 120 VA\r\n• Size: 230x250x140(h)mm\r\n• Weight: 8Kg ((With separate power adapter))', '4', '1', 'All tubes headphone & speak amp', '0000000111', '2008-08-08', '1');
INSERT INTO `products` VALUES ('13', 'LD-X1', '<SPAN CLASS=\"title\">Description</SPAN>\r\nLD X1 is the current flagship solid state amplifier from Little Dot. This amp was designed to drive most of the flagship headphone. Not only it has a lot of power, but it is very detail at the same time. It drives both high or low-impendence dynamic headphone, and it also drives planar headphones perfectly as well.\r\n\r\nLD X1 uses discrete component design in order to achieve the highest standard both on charts and actual listening experience, and this is something that an integrated circuit design would be having difficulties to reach such a standard. Also, due to the working state cannot be changed on an integrated circuit design, it cannot be an actual “pure class-A” amplifier.\r\n\r\nThe components, including Kendeil, Vishay, ELNA and SILMIC II silk capacitors, were carefully chosen for maximum synergy; delivering purity of sound, bombastic dynamics, silky details, and three dimensional sound-stage imaging.\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Inputs: \r\n	(1) 3-pin XLR\r\n	(2) RCA\r\n• Outputs: \r\n	(1) 4-pin XLR headphone output\r\n	(2) 6.35mm TRS headphone output\r\n	(3) 3-pin XLR headphone/pre-amp output\r\n• Total Distortion: 0.001% (2V rms @ 1000Hz)\r\n• Signal to Noise: 98dB\r\n• Frequency Response: 5 Hz – 100 KHz (-3dB), 10 Hz – 50 KHz (-1dB)\r\n• Output Power: 6W per channel @ 32 Ω, 1W per channel @ 300 Ω\r\n• Gain Settings: High (5x) and Low (3x)\r\n• Power Consumption: 60 VA\r\n', '3', '3', 'The flagship Solid State headphone amplifier', '0000000122', '2008-08-08', '1');
INSERT INTO `products` VALUES ('14', 'MK6+', '<SPAN CLASS=\"title\">Description</SPAN>\r\nThe Little Dot MK VI+ is one of our best-selling headphone amplifier/pre-amplifier in the Little Dot MK-series. A fully balanced design, the Little Dot MK VI+ has exceptional dynamic range and can produce clean amplitudes of 70Vp-p into 120 ohms! The balanced Class-A SEPP (single-ended push pull) OCL (output capacitor-less) circuit topology delivers rich tonality and powerful force for maximum dynamics and low frequency impact. Also, MK VI+ provides the upgrade version and it saves you a lot of work to modify the machine, and upgrade pre-amp tubes is also available upon request\r\n\r\n<SPAN CLASS=\"title\">SPECIFICATIONS</SPAN>\r\n• Available in either Black (default) or Silver\r\n• Fully Balanced Architecture\r\n• SEPP (Single-ended Push Pull) OCL (Output CapacitorLess) in Class-A\r\n• Active 2 fan cooling\r\n• Driver Tubes: 2x 6H9C\r\n• Power Tubes: 4x 6080WC\r\n• Inputs:\r\n	Balanced: 2x 3-pin XLR\r\n	Single-ended: 2x RCA\r\n• Outputs:\r\n	Balanced: 4-Pin XLR\r\n	Balanced Pre-Amp: 2x 3-pin XLR\r\n• Single-ended: 1/4″ (6.35mm) TRS Stereo jack\r\n• Frequency Response:Input Impedance: 50K Ω\r\n	5Hz – 80KHz (-3dB)\r\n	10Hz – 30KHz (-1dB)\r\n• Pre-Amplifier Output Impedance: 600 Ω\r\n• THD+N:Power Output:\r\n	0.02% (2Vrms @ 1000Hz)\r\n	0.06% (10Vrms @ 1000Hz)\r\n	0.3% (20Vrms @ 1000Hz)\r\n• Output Power: 5W per channel in 120 Ω\r\n• Power Consumption: 25 VA\r\n• Size: 350x290x140(h)mm\r\n• Weight: 9.6KG(about 21.15 pounds)\r\n• One Year Official Little Dot Warranty\r\n\r\nUpgrade version includes:\r\n• 4 Mundorf MCap SUPREME Silver Oil as coupling capacitors\r\n• Silver plated teflon wiring\r\n• WBT Silver solder on the signal nodes\r\n• Pre-amp tubes: Mullard CV4024 (optional, and socket convertor would be included)', '1', '1', ' •Fully Balanced Circuit<BR>\r\n•Use as pre-amp', '0000000222', '2008-08-08', '4');
INSERT INTO `products` VALUES ('15', 'MK8-SE', '<SPAN CLASS=\"title\">Description</SPAN>\r\nThe Little Dot MK 8 SE further specializes our Little Dot MK 6 platform for no-compromise performance with high impedance headphones. Fully balanced design with single-ended headphone functionality as well, the Little Dot MK VIII SE is also dual-mono with independent amplifiers with their own isolated toroidal transformer power supplies. An output capacitor-less design minimizes components in the signal path, delivering a “pure” signal free from unwanted distortion and color. The Little Dot MK VIII SE’s sound signature is designed to be provide a reference-level of transparency with a touch of tube warmth and tonal richness.\r\n\r\nKey Point:\r\n• All the balanced socket on the machine is reliable NIUTRIK™,Swiss XLR socket.\r\n• Volume control potentiometer from ALPS™,Japan.\r\n• Resistance from DALE™,USA. Capacitance from WIMA™/ERO™/CHEMI-COM™, Germany.\r\n• Ample sound field, high accuracy, excellent gradations, and nice control ability.\r\n• Both working as headphone amplifier and balanced pre-amplifier.\r\n• Gold award winner of 1st Hong Kong “Headphone Amplifier King”.  \r\n\r\n<SPAN CLASS=\"title\">SPECIFICATIONS</SPAN>\r\n• Available in either Black  or Silver\r\n• Fully Balanced, Dual-Mono Architecture\r\n• Inputs:\r\n	Balanced: 2x 3-pin XLR\r\n	Single-ended: 2x RCA\r\n• Outputs:\r\n	Balanced: 4-Pin XLR\r\n	Balanced Pre-Amp: 2x 3-pin XLR\r\n	Single-ended: 1/4″ (6.35mm) TRS Stereo jack\r\n• Input Impedance: 50K  Ω\r\n• Frequency Response:\r\n	5Hz – 80KHz (-3dB)\r\n	10Hz – 30KHz (-1dB)\r\n• Pre-Amplifier Output Impedance: 600  Ω\r\n• THD+N:Signal-to-Noise: \r\n	96 dB0.01% (2Vrms @ 1000Hz)\r\n	0.03% (10Vrms @ 1000Hz)\r\n	0.2% (20Vrms @ 1000Hz)\r\n• Voltage Swing: 60V p-p\r\n• Power Output:\r\n	2W per channel @ 600 Ω\r\n	1W per channel @ 300 Ω\r\n• Power Consumption: 100 VA\r\n• Size: 350x290x140(h)mm\r\n• Weight: 9.6KG(about 21.15 pounds)\r\n\r\nUpgrade version includes:\r\n• 4 Mundorf MCap SUPREME Silver Oil as coupling capacitors\r\n• Silver plated teflon wiring\r\n• WBT Silver solder on the signal nodes\r\n• Pre-amp tubes: Mullard CV4024 (optional)', '1', '1', '•Fully Balanced Circuit<BR>\r\n•Use as pre-amp', '0000000133', '2008-08-08', '5');
INSERT INTO `products` VALUES ('16', 'MK3+', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nMK3+ used a combined framework. The tube front stage presents sweet sound performance and transistor back stage supports high drive power. This framework guaranteed both high-current to drive low resistance headphones and high voltage swing for high resistance headphones.\r\nThe tube parts of MK3+ is set up with a pair of 6C4 tubes.Transistor parts is a PNP/NPN discrete symmetrical Class-A amplifier circuit.\r\n\r\nCombined framework keeps advantages form both tube and transistor. Especially it performs excellently when driving low resistance headphones. \r\n\r\nMK3+ has two versions: with Bluetooth wireless input or not. The Bluetooth Version has a v4.2 Bluetooth module for good wireless utility.\r\n\r\nOxidation treated surface and golden plated tube guard board.\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input ports: RCA*2\r\n• Output ports: 6.35mm(1/4inch)*1, (Pre-Amplifier)RCA*2 \r\n• Input resistance: 10Kohm\r\n• THD: 0.001%  2V@RMS 1000Hz\r\n• SNR: 95dB\r\n• Frequency Response: 5Hz --- 100KHz(-1dB)\r\n• Output power: 2.5W@32ohm\r\n	1.8W@120Ω\r\n	0.8W@300Ω\r\n• Adapt headphone resistance: 32Ω ~ 600Ω\r\n• Magnification: 9@GAIN=HIGH, 4.5@GAIN=LOW\r\n• Power consumption: 25VA\r\n• Size: 245x165x120(H)mm\r\n• Weight: 3Kg\r\n\r\n', '2', '1', 'Hybrid tube', '0000000111', '2008-08-08', '3');
INSERT INTO `products` VALUES ('17', 'MK9', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nLittle Dot MK9 uses 3 tubes; the pre-amp tube: 6N9P, and the power-amp tubes: 6080*2. The input signal is the audio signal from the CD player or DAC, an amplified output signal used to drive headphones. You can also use the MK 9 as pre-amp, just use its RCA connection to connect a power amp.\r\n\r\nThe circuit output dynamic than the cathode output generally large (undistorted swing: 30Vp-p), due to the cancellation of the output capacitance, low frequency response can dive deeper and it provides solid bass, and mid can be more transparent.\r\n\r\nBut in order to make the circuit in the case of direct coupled DC level is zero, need symmetrical supply complex. In order to stabilize the operation of the circuit, and the machine also adopts a “zero servo tracking circuit”. In order to ensure the safety of the output load, relay protection circuit and output protection special chip.\r\n\r\nThe machine output tube uses a new production of the RCA company 50 years antique tube (NOS), is one of the best tubes in the world.\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n•  Input terminal: RCA\r\n•  Output terminal:RCA (pre amplifier with); 6.35 earphone socket.\r\n•  Frequency response: 12HZ—100KHZ (-1dB)\r\n•  Distortion: 0.05% (300Ω, 80 mW)\r\n•  The maximum output power of :A. 300 mw (600/300Ω);B. 350 mw (120Ω);C. 250 MW (32Ω)\r\n•  Output impedance: 32 ohm – 600 ohm\r\n•  Voltage: 110V or 220V (user specified)\r\n•  Power consumption: 80 VA\r\n• Size: 300 (D) X220 (W) X150 (H) mm\r\n• Weight: 4 Kg\r\n', '1', null, '•High-current output<BR>\r\n•Use as pre-amp', '0000000011', '2008-08-08', '3');
INSERT INTO `products` VALUES ('18', 'MINI4', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nLittleDot Mini-4 Music Center contains 4 devices:\r\n1•  DP-4 Stream Media Player\r\nBase on Raspberry Pi 4B, DP-4 has a Quad Core 1.5Ghz 64bit ARM Cortex-A72 CPU. This powerful processor makes DP-4 readily processes all kinds HQ audio data. DP-4 has a AK4137 SRC module for PCM - DSD format conversion. The low jitter clock recovery circuit ensured clock working on a high stable condition during stream playing.\r\nDP-4 supports USB device like Flash Disk and portable hard-drive. Otherwise, DP-4 has powerful wireless function for Bluetooth, LAN, DLAN, Air-Play etc.\r\n<HR>\r\n2• DA-4 Digital Decoder\r\nDecoder scheme is on AK4493 DAC, PCM support is up to 768KHz/32bit, and DSD up to 256Bit. This DAC chip is a new product belong to AKM VELVET SOUND series. By the OSRD(over sampling rate doubly) tech, AK4493 can substantially reduce interference noise support the player more clear sound performance.\r\n<HR>\r\n3• AM-4 Headphone Amplifier\r\nAM-4 is designed with entire discrete symmetrical Class-A circuit without any molectron. This circuit has better Instantaneous response speed and lower crossover distortion.\r\n<HR>\r\n4• PO-4 Power Supply\r\nEven for a mini size music center, we added a linear power in the set. Compared to general switch power supply, linear power supply with high-power ring transformer can ensure a much stable driving power for the system.\r\n<HR>\r\nMini-4 is a set of mini size music center. But we set every module same as the full-size system. Complete sound performance and portable size, this is the most excellent advantage of this product.\r\n\r\n<SPAN CLASS=\"title\">Accessories:</SPAN>\r\n• RJ45 network cable(for I²S connect)*1\r\n• 3-pin power cable*1 \r\n• Devices connect power cable*3\r\n• Main power cable(Aviation plug)*1\r\n• 3.5 to 3.5 resistance adaptor*1 (for low resistance headphones).\r\n• 3.5 to 6.35 adaptor*1\r\n', '5', '1', '4 in 1 Stream Music Center', '0000000111', '2008-08-08', '2');
INSERT INTO `products` VALUES ('19', 'D300', '<SPAN CLASS=\"title\">Description</SPAN>\r\nThe full Littledot D300 set consists of two parts:\r\n1. D300 pre amplifier\r\n2. D300 power amplifier\r\nThe above two can be purchased separately, but we strongly suggest that you use it with our pre-amp.\r\n\r\nLittle Dot’s D300 mono block power amp is little, but it surely provides a lot of power!\r\n\r\nThe D300 preamplifier uses 6J1 vacuum tubes as the input amplifier. The voltage drive of the BUF makes the front stage not only have sufficient driving force, but also have a warm and sweet sound, which effectively improves the sound quality of the power amplifier.\r\n\r\n<SPAN CLASS=\"title\">Specifications of D300 Pre Amp</SPAN>\r\n• THD+N: 0.01 % 1kHz, 2 V rms, 600Ω\r\n• SNR: 99 dB\r\n• Voltage gain: 1kHz 2.2 times\r\n• Frequency Response: 10 100kHz, 600Ω ±1 dB\r\n• ZIN: 100 kΩ\r\n• Volume: 300*175*70mm\r\n• Weight: 2.23 Kg\r\n<HR>\r\n<SPAN CLASS=\"title\">Specifications of D300 Power Amp</SPAN>\r\n• Rated output power: 20 20kHz, THD+N<0.1%, 4Ω 300W\r\n• THD+N: 0.03 % 1kHz, 50W, 8Ω\r\n• SNR: 98 dB\r\n• Voltage gain: 1 kHz 31 dB\r\n• Frequency Response: 20 20kHz, 8Ω ±1 dB\r\n• ZIN: 10 kΩ\r\n• Native efficiency: 200W @ 8Ω 91 %\r\n', '9', null, 'D-Class Digital Amplifier', '0000000111', '2017-08-08', '1');
INSERT INTO `products` VALUES ('20', 'CU-KIS', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/CU-KIS/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page6.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page7.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page8.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page9.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page10.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page11.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page12.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page13.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page14.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page15.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page16.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-KIS/page17.jpg\" style=\"max-width:100%\">\r\n</div>\r\n', '8', null, 'Flag IEM with Dual Diamond Dynamic Armature', '0000000222', '2008-08-08', '5');
INSERT INTO `products` VALUES ('21', 'CU-GYFU', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/CU-GYFU/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page6.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page7.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page8.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page9.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page10.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page11.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-GYFU/page12.jpg\" style=\"max-width:100%\">\r\n</div>\r\n', '8', null, 'Three Dynamic Drivers Headphone', '0000000222', '2008-08-08', '1');
INSERT INTO `products` VALUES ('22', 'CU-WYN', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/CU-WYN/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page6.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page7.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page8.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page9.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page10.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page11.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page12.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page13.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-WYN/page14.jpg\" style=\"max-width:100%\">\r\n</div>\r\n', '8', '1', 'Low bass IEM', '0000000011', '2010-08-08', '3');
INSERT INTO `products` VALUES ('23', 'CU-CEN', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/CU-CEN/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page6.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page7.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page8.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page9.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page10.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page11.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page12.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page13.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page14.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page15.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-CEN/page16.jpg\" style=\"max-width:100%\">\r\n</div>\r\n', '8', null, 'Best IEM from Little Dot for vocal music', '0000000022', '2010-08-08', '4');

-- ----------------------------
-- Table structure for `product_type`
-- ----------------------------
DROP TABLE IF EXISTS `product_type`;
CREATE TABLE `product_type` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of product_type
-- ----------------------------
INSERT INTO `product_type` VALUES ('1', 'Tube Headphone Amplifier');
INSERT INTO `product_type` VALUES ('2', 'Hybrid Headphone Amplifier');
INSERT INTO `product_type` VALUES ('3', 'Solid State Amplifier');
INSERT INTO `product_type` VALUES ('4', 'Headphone & Speaker Dual Use');
INSERT INTO `product_type` VALUES ('5', 'DAC & Streaming');
INSERT INTO `product_type` VALUES ('6', 'Power Regenerator');
INSERT INTO `product_type` VALUES ('7', 'CD Player');
INSERT INTO `product_type` VALUES ('8', 'Headphone & IEMs');
INSERT INTO `product_type` VALUES ('9', 'Speaker Amplifier');
