/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50714
Source Host           : localhost:3306
Source Database       : littledot_web

Target Server Type    : MYSQL
Target Server Version : 50714
File Encoding         : 65001

Date: 2021-11-27 20:34:05
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `products`
-- ----------------------------
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `contents` text,
  `class` tinyint(3) unsigned zerofill DEFAULT NULL,
  `type` tinyint(3) DEFAULT NULL,
  `description` varchar(128) DEFAULT NULL,
  `price` decimal(10,0) unsigned zerofill DEFAULT NULL,
  `ttm` date DEFAULT NULL,
  `position` tinyint(3) unsigned zerofill DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of products
-- ----------------------------
INSERT INTO `products` VALUES ('1', 'MK2', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nLittle Dot MK II uses the 6J1 pentode as the pre-amp tubes, and the double diode triode 6n6. This combination forms a SEPP (Single-Ended Push Pull) OTL Class-A amplifier. The SEPP circuit design greatly increases sound quality, dynamic range, output impedance, and lower distortion over the Little Dot II.\r\n\r\nThe Little Dot MK II now also provides gain control of 3, 5, and 10 via internal DIP switches for fine-tuning so you can maximize synergy with almost any headphone you have, whether it be 32 ohms or 600! Not only it works great as a headphone amplifier, it also works as a pre-amplifier, and the user can link it to your power amplifier to tune your current system. The double anodic aluminum oxidation provides chassis quality touch and smooth surface.\r\n\r\nThe Little Dot MK II also gives user to enjoy tube-rolling, you can stick with the original 6JI, or you could swap with WE403A/B, GE5654, M8100, CV4010, EF95, and etc. At its factory jumper setting, and with jumper pins shorted, EF92, CV131, and all equivalents and drop-in replacements!\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n1. <A HREF=\"https://www.head-fi.org/showcase/little-dot-mk-ii.12097/\" target=\"_blank\">Review of Little Dot MKII: Little Dot MK II Review @ Head-Fi </A>\r\n2. <A HREF=\"https://www.youtube.com/watch?v=65y_2yc_vZs&t=7s/\" target=\"_blank\">Cheap Tubes for BIGGER Soundstage? Little Dot MK II Review! @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input: Gold-Plated Unbalanced Phono (RCA) Jacks\r\n• Output: 1/4″ Gold-Plated Stereo Headphone out, RCA Jacks (for pre-amp use)\r\n• Pre-Amplifier Gain: 3-10x (also controlled via gain switches)\r\n• Frequency Response: 300 ohm (-1dB)\r\n• THD+N: 0.1% (50mW into 300 ohms)\r\n• Output Power:\r\n	a) 300 mW   (600/300 Ω)\r\n	b) 200 mW   (120 Ω)\r\n	c) 100 mW   (32  Ω)</div>\r\n• Output Impedance:\r\n• Suitable Headphone Impedance: 32 ohm – 600 ohm\r\n• Pre-amp impedance: 10 K ohm\r\n• Fuse: 1A (within the power plug slot)\r\n', '001', '1', 'All tubes headphone amp & pre amp', '0000000080', '2008-08-08', '001');
INSERT INTO `products` VALUES ('2', 'LD1+', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe Little Dot I+ is a hybrid transistor-vacuum tube headphone amplifier, which combines the smooth, musical sound of tubes with the high output current of transistors. The vacuum tube stage is run in Class-A, the MC33078 operational amplifier (socketed) provides voltage amplification, and BD139/BD140 transistors serve as output buffers.\r\n\r\nThe Little Dot I+ is specifically designed and optimized for driving low impedance headphones that require high current to perform to their full potential. Depending on how the switches are configured, three different families of vacuum tubes can be used (EF95, EF92, and 408A). With two gain settings and DIP switches for vacuum tube rolling, the Little Dot I+ offers versatility and incredible sound quality in a tiny footprint!\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<A HREF=\"https://www.youtube.com/watch?v=DDSPXOyyUt4&t=96s\" target=\"_blank\">LittleDot 1+ Review: Best Tube Amp under $170?  @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input: Gold-Plated Unbalanced Phono (RCA) Jacks\r\n• Output: 1/4\" Gold-Plated Stereo Headphone out\r\n• Vacuum  Tubes: 6JI (default) EF92 or WE408 as upgrades\r\n• Frequency Response: 10HZ - 50KHz (-3 dB)\r\n• THD+N: \r\n	0.2%: 1     Vrms @ 1000Hz\r\n	0.6%: 3     Vrms @ 1000Hz\r\n	1.0%: 5     Vrms @ 1000Hz\r\n• Gain: 3.5x, 7x\r\n• Power Output: \r\n	800mW @ 32Ω\r\n	300mW @ 120Ω\r\n	150mW @ 300Ω\r\n• Recommended Headphone Impedance: 8 – 600Ω\r\n• Power Consumption: 15VA\r\n• Size: 180x97x10(h) mm\r\n• Weight: 1.5 kg', '001', '2', 'Hybrid tube headphone amp', '0000000080', '2008-08-08', '002');
INSERT INTO `products` VALUES ('3', 'MK3', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nMK3 is an “all vacuum tube” amplifier. \"ALL\" means that its pre and post stage are tube amplification. The MK3 can both work as headphone amplifier and vacuum tube pre-amplifier. It\'s design with SEEP circuit frame. Input stage used GE5654 form GE™, and final output stage is 6H6π. This framework guaranteed both high-current to drive low resistance headphones and high voltage swing for high resistance headphones.\r\n\r\nMK3 is a long-life product in our product line, it is a classic design of SEEP circuit frame, and all the components in this circuit are famous and reliable. The volume control potentiometer from ALPS™,Japan. E-Cap as filter capacitors from RUBYCON™,Japan. Coupling capacitance from ERO™, Germany. Final stage output capacitors form CHIEMI-COM™,Germany and calibrating capacitors form WIMA™,Germany.\r\n\r\nIt has been once praised as “Lucky Product” by Stereophile magazine.\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n1. <A HREF=\"https://www.youtube.com/watch?v=7MeH9C4_Zi0\" target=\"_blank\">Little Dot MK 3 Tube Amplifier Review and Tube Rolling @ Youtube</A>\r\n2. <A HREF=\"https://www.youtube.com/watch?v=wO2il7SRzn4\" target=\"_blank\">Little Dot MK III Headphone Tube Amplifier Review @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input ports: RCA*2\r\n• Output ports: \r\n	6.35mm(1/4inch)x1\r\n	Pre-Amplifier) RCA x2 \r\n• Magnification: 3x~10x\r\n• Frequency Response: 12Hz --- 100KHz (300odm -1dB)\r\n• THD: 0.15%  (300odm 80mW)\r\n• SNR: 96dB\r\n• Output Power: \r\n	100mW@32Ω\r\n	300mW@120Ω\r\n	350mW@300/600Ω\r\n• Output resistance: 10KΩ for pre-amplifier, 32Ω~600Ω for headphones\r\n• Fuse: 1A (inside power supply socket)\r\n• Size: 270(L)x175(W)x123(H)mm\r\n• Weight: 3Kg\r\n', '001', '1', 'All tube headphone amp & pre amp', '0000000090', '2008-08-08', '003');
INSERT INTO `products` VALUES ('4', 'LD-H1', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nLD-H1 is a tube-transistor combined fully balanced headphone amplifier. The front stage tube part is the famous NOS tube 6SN7 from SYLNAVIA™,USA. Back stage part is designed with entire discrete symmetrical Class-A circuit without any molectron. This circuit has better Instantaneous response speed and lower crossover distortion. LD-H1 has a compatible framework for both balanced and non-balanced system. The machine contained XLR balanced input/output ports and non-balanced RCA input and 6.35mm output.\r\n\r\nThe design scheme LD-H1 is “double single channel”. From power supply to amplifier, every circuit unit is exactly independent to avoid crosstalk. Combined framework keeps advantages form both tube and transistor. Especially it performs excellently when driving low resistance headphones. \r\n\r\nAs a balanced amplifier, LD-H1 contained 4 independent amplification units with own transformer supply. The current direction through each amplification unit is opposite. This scheme offsets the fluctuation of voltage, makes power supply more stable and reduces power supply internal resistance intermodulation. It affects the sound performance more clear and roomy. \r\n\r\nThe components of this amp are also very well chosen. Classic style appearance with textured wooden cover. Famous BC E-Cap as filter capacitors from Philips™. M-cap EVO audio special-purpose coupling capacitance from Mundorf™, Germany.\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<A HREF=\"https://headfonics.com/little-dot-ld-h1-review/\" target=\"_blank\">Little Dot LD H1 Review @ Headfonics</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input Ports: RCA x2\r\n• Balance: XLR 3p x2\r\n• Unbalanced: RCAx2\r\n• Output Terminal:\r\n	Balance: XLR 4p x1\r\n	Unbalanced: 6.35mm x1\r\n	Pre-output: Balance: XLR 3p x2\r\n	Input impedance: 10 K ohm\r\n• Distortion: 0.001% (output: 2V rms 1000Hz)\r\n• Signal to noise ratio: 108dB\r\n• Frequency response: 10Hz – 50KHz (-0.1dB)\r\n• Output Power:\r\n	5W (32 Ω)\r\n	1.8W (120 Ω)\r\n	0.8W (300 Ω)\r\n	0.4W (600 Ω)\r\n• Adapted headphone impedance: 16 ohm ~ 600 ohms\r\n• Gain:\r\n	Gain = HIGH: 9\r\n	Gain = LOW: 4.5\r\n• Power consumption: 25 VA\r\n• Size: 300x210x140(H)mm\r\n• Weight: 4.5Kg', '001', '2', 'The flagship hybrid headphone amp', '0000000150', '2017-08-08', '004');
INSERT INTO `products` VALUES ('5', 'LD-Y2', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe LittleDot LD-Y2 is a headphone and loud speaker dual-use amplifier with 300B tubes. In order to achieve the best performance, its power unit and amplification unit are independent. The power supply of LD-Y2  uses the tube rectification. It\'s come from Soviet Union, 5U4G. \r\n\r\nAs we all know, 300B is a very good power tube for the amplifier. As the core of  LD-Y2, we chooses JJ300B, which is the industry-leading, from Czech. In the selection of the preamp tube, according to the original recommendation of 300B usage, we choose RCA 6SH7 as the preamp tube for it.\r\n\r\nThe other parts of LD -2 are also very elaborate, including:\r\n  1. Swiss Lundal™ input transformer\r\n  2. Mundorf™  oil immersed capacitor\r\n  3. Kiwame™ resistors\r\n  4. Germany WBT™ silver solder\r\n  5. Japan Furutech™ AC Socks\r\n  6. DACT™ Audio Attenuators\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<div style = \"background: #efefed;\">	\"The LD Y2 focuses on curing the low-frequency problem for all kinds of hard to driver headphones. The medium and high frequency details are excellent, the medium frequency density is moderate, and the “tube smell” is  obvious. It can be said that it brought quite a surprise, especially the  Beyerdynamic T1 and HiFi-Man HE1000, which are the best performance I\'ve ever heard.\" </div> ---- from **af2000** @ erji.net\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input terminals.\r\n• XLR balanced input x2\r\n• RCA unbalanced input x2 \r\n• Headphone output terminals.\r\n	XLR (4 cores) x1 (balanced headphone output)\r\n	6.35 (3 core) x1 (unbalanced headphone output)\r\n• The speaker output terminals: a total of four left and right channels\r\n• Distortion: 0.1% (1000Hz) \r\n• Signal-to-noise ratio: 98dB\r\n• Frequency response:\r\n	20Hz - 20KHz (-0.2dB)\r\n	10Hz - 50KHz (-2dB) \r\n• Output power:\r\n	10W (8 Ω) 	\r\n	6W (120 Ω)\r\n	3W (300 Ω)\r\n• Amplification:\r\n	GAIN=HIGH: 7\r\n• GAIN=LOW: 4\r\n• Power consumption: 150 VA\r\n• Size: 350x210x220(h)mm (This is the size of one unit, the amp + power supply total of two units)\r\n• Weight: 23 Kg (including the amp + power supply, together with the total weight of packaging and accessories)', '003', '1', '300B headphone & speaker amplifier', '0000000199', '2017-08-08', '005');
INSERT INTO `products` VALUES ('6', 'DAC-7', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nDue to LittleDot Audio years of analog audio design experience, our DAC products also have a unique feature that we call it \"analog taste\".\r\n\r\nThe flagship ES9038PRO SABRE DAC sets a new benchmark for audio excellence with the industry’s highest dynamic range (DNR), in a 32-bit, 8-channel DAC. These parameters make the ES9038PRO excellent in terms of resolution performance. With our experience in analog circuits, the DAC7 strikes a good balance between high detailing and natural musicality.\r\n\r\n<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/DAC-7/6.jpg\" style=\"max-width:100%\">\r\n</div>\r\n\r\n', '004', '1', 'An ESS9038PRO Solutions DAC', '0000000192', '2018-08-08', '006');
INSERT INTO `products` VALUES ('7', 'LDP-1000', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThis is the HiFi top purifying power supply, it convert the AC power to DC power, through the MCU composite waveform convert to the stable AC power at 50 or 60Hz.\r\n\r\nThis is our third generation of power regenerator, and we’ve adopted SCALE™ IGBT method from Power Intergration. The LDP-1000 has the following functions, automatic recovery after over-current protection, which gives the regenerator more reliable than that of the previous generation products.\r\n\r\nIt has the function of automatically stable the frequency and voltage, active energy compensation, over-current protection, automatic recovery. With this method, we can avoid the disadvantages of dynamic compression, supply our equipment with clean power and the background will be pitch black.\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Output Power: 1000VA\r\n• Power Supply Distortion: <= 1%\r\n• Power Supply Stability: 2%\r\n• Power Factor: 0.95\r\n• Maximum Efficiency: 95%\r\n• Voltage Tolerance Boundary: 185 – 255 V\r\n	From no-load to 100% full load, the instantaneous output voltage fluctuations < 6%, recovery cycle less than 2 sine wave cycle.\r\n• Output voltage: 110V or 220V\r\n• Output frequency: 50Hz or 60Hz\r\n• Output Sockets: 8 US sockets\r\n	Protection function: It has conventional protection functions such as overheating, overload, short circuit, over-voltage, under-voltage, etc.\r\n	Note: Due to the weight of the power regenerator, it is very difficult for us to lower the price of this wonderful unit. However, if you’re not in a rush, ocean freight will be able to save you a lot of money. The downside of that is that we will not be able to provide you any tracking number, and it could take up to 40 days for your product to arrive. Please contact us if you’d wish to proceed with ocean freight, thank you!\r\n', '005', '1', 'Purification and regeneration power supply', null, '2018-08-08', '007');
INSERT INTO `products` VALUES ('8', 'CDP-2', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe Littledot CDP-2 is a CD turntable with a Philips DAISY GF-8 CD core. As a pure turntable, although this means it needs an additional DAC to work, the design gives you the opportunity to employ a different DAC with it and try different flavors.\r\nPhilips DAISy GyFalcon 8, a high end module dedicated to CD applications. It has been meticulously tested to reach an excellent playability and reliability.  A DSA high level interface is available for this module. \r\nGF-8 Key features: \r\n	• Extra slim loader\r\n	• Excellent reliability\r\n	• Low mechanical noise\r\n	• DSA Interface (High Level protocol)\r\n	• Extremely good playability and disc acceptance\r\n	• Compatibility with protected discs\r\n	• I2S and SPDIF signals available\r\n	• Fast average access time\r\n	• MP3 DISC playback\r\n	• Excellent ratio quality/price\r\n	• RoHS compliant\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• S/PDIF output terminals.\r\n• BNC output socket\r\n• RCA output socket\r\n• Optical output socket\r\n• Coaxial output impedance:  BNC/RCA: 75Ω\r\n• S/PDIF output level:  BNC/RCA : > 500 mV (rms)\r\n• Output sampling frequency:  44.1 KHz\r\n• Power Consumption:\r\n	Working: 10 VA\r\n	Standby: 3 VA\r\n• Fuse: 1A (built-in in the power socket)\r\n• Size: 275X217X61(H) mm\r\n• Net weight: 2 .1Kg  \r\n• Gross weight: 2.9 Kg', '006', '1', 'Philips Daisy GF8 Module', '0000000011', '2010-08-08', '008');
INSERT INTO `products` VALUES ('9', 'CU-RAD', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/CU-RAD/page1.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page2.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page3.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page4.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page5.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page6.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page7.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page8.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page9.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page10.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page11.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page12.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page13.png\" style=\"max-width:100%\">\r\n<img src=\"/static/products/CU-RAD/page14.jpg\" style=\"max-width:100%\">\r\n</div>\r\n', '007', '1', 'Multiayer Nanomaterial IEM', '0000000012', '2020-01-01', '009');
INSERT INTO `products` VALUES ('10', 'LD-ZERO', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/LD-ZERO/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page6.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/LD-ZERO/page7.jpg\" style=\"max-width:100%\">\r\n</div>', '001', '1', 'All In One headphone amp with DAC & Blueteeth', '0000000111', '2021-11-11', '010');
INSERT INTO `products` VALUES ('11', 'MK3-SE', '<div style=\"\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  width:100%;\r\n\">\r\n<img src=\"/static/products/MK3-SE/page1.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page2.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page3.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page4.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page5.jpg\" style=\"max-width:100%\">\r\n<img src=\"/static/products/MK3-SE/page6.jpg\" style=\"max-width:100%\">\r\n</div>\r\n\r\n', '001', '1', 'Hybrid tube balanced headphone amp', '0000000123', '2008-08-08', '011');
INSERT INTO `products` VALUES ('12', 'LD3-SE', '<SPAN CLASS=\"title\">Introduction</SPAN>\r\nThe Little Dot LD III SE uses the NOS Telefunken EL152 antique tubes as power output tubes; for pre-amplification, it uses the Western Electric WE408A . These tubes are now legendary “artifact”, and we only have 150 sets of new NOS inventory, so the machine is a true “limited edition.”\r\n\r\nThe machine uses a specially designed Z11 core output transformer, coupling capacitor uses Mundorf silver oil capacitors, and resistors are Kiwame for AUDIO-specific resistors. Teflon silver wire is used within the machine, and the German silver solder. Headphone output section, using our developed “intelligent recognition impedance” proprietary technology that can automatically detect impedance headphones, and switch to the appropriate interface.\r\n\r\nTelefunken EL152 output power (larger than the famous 300B); sound excellent, with so much musical detail. Such tubes are antique collection!\r\n\r\n<SPAN CLASS=\"title\">Reviews</SPAN>\r\n<A HREF=\"https://www.youtube.com/watch?v=ZbZs2BoX39k\" target=\"_blank\">These are Limited Version for a Reason ! Little Dot LD3SE tube integrated amplifier review by Jay\'s iyagi @ Youtube</A>\r\n\r\n<SPAN CLASS=\"title\">Parameters</SPAN>\r\n• Input terminals:\r\n	RCA x2\r\n• Output terminal :\r\n	1,6.35 x1 (headphone output)\r\n	2, RCA x2 (Pre Out)\r\n• Distortion: 0.1% (1000Hz)\r\n• Signal to Noise Ratio: 96dB\r\n• Frequency response:\r\n	1,20Hz – 20KHz (-1dB)\r\n	2,20Hz – 40KHz (-2dB)\r\n• Output power:\r\n	Maximum output power: 10W + 10W\r\n• Rated output power:\r\n	10W (8 Ω)\r\n	6W (32 Ω)\r\n	2W (300 Ω)\r\n• Magnification:\r\n	GAIN = HIGH: 10\r\n	GAIN = LOW: 5\r\n• Power consumption: 120 VA\r\n• Size: 230x250x140(h)mm\r\n• Weight: 8Kg ((With separate power adapter))', '001', '1', 'All tubes headphone & speak amp', '0000000111', '2008-08-08', '012');
